In [ ]:
import pandas as pd

df = pd.read_csv("../data/mental_health_dataset.csv")

df.head()
df['label'].value_counts()

In [1]:
df = pd.read_csv("../data/mental_health_dataset.csv")

print(df.head())

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/mental_health_dataset.csv")

print(df.head())

         Timestamp  Gender        Country Occupation self_employed  \
0  8/27/2014 11:29  Female  United States  Corporate           NaN
1  8/27/2014 11:31  Female  United States  Corporate           NaN
2  8/27/2014 11:32  Female  United States  Corporate           NaN
3  8/27/2014 11:37  Female  United States  Corporate            No
4  8/27/2014 11:43  Female  United States  Corporate            No

  family_history treatment Days_Indoors Growing_Stress Changes_Habits  \
0             No       Yes    1-14 days            Yes             No
1            Yes       Yes    1-14 days            Yes             No
2            Yes       Yes    1-14 days            Yes             No
3            Yes       Yes    1-14 days            Yes             No
4            Yes       Yes    1-14 days            Yes             No

  Mental_Health_History Mood_Swings Coping_Struggles Work_Interest  \
0                   Yes      Medium               No            No
1                   Yes      Medium               No            No
2                   Yes      Medium               No            No
3                   Yes      Medium               No            No
4                   Yes      Medium               No            No

  Social_Weakness mental_health_interview care_options
0             Yes                      No     Not sure
1             Yes                      No           No
2             Yes                      No          Yes
3             Yes                   Maybe          Yes
4             Yes                      No          Yes

In [4]:
print(df.columns)

Index(['Timestamp', 'Gender', 'Country', 'Occupation', 'self_employed',
       'family_history', 'treatment', 'Days_Indoors', 'Growing_Stress',
       'Changes_Habits', 'Mental_Health_History', 'Mood_Swings',
       'Coping_Struggles', 'Work_Interest', 'Social_Weakness',
       'mental_health_interview', 'care_options'],
      dtype='object')

In [5]:
df['status'] = df['Growing_Stress']

In [6]:
df[['Growing_Stress','status']].head()

  Growing_Stress status
0            Yes    Yes
1            Yes    Yes
2            Yes    Yes
3            Yes    Yes
4            Yes    Yes

In [7]:
label_mapping = {
    'No': 0,      # Low Anxiety
    'Maybe': 1,   # Moderate Anxiety
    'Yes': 2      # High Anxiety
}

In [8]:
df['anxiety_level'] = df['status'].map(label_mapping)

In [9]:
df[['status','anxiety_level']].head()

  status  anxiety_level
0    Yes              2
1    Yes              2
2    Yes              2
3    Yes              2
4    Yes              2

In [10]:
print(df['anxiety_level'].value_counts())

anxiety_level
1    99985
2    99653
0    92726
Name: count, dtype: int64

In [11]:
df.to_csv("../data/processed_dataset.csv", index=False)

In [12]:
label_mapping = {

'Normal': 0,

'Stress': 1,

'Anxiety': 1,

'Depression': 2,

'Suicidal': 2,

'Bipolar': 2,

'Personality disorder': 2

}

df['anxiety_level'] = df['status'].map(label_mapping)

In [13]:
df['anxiety_level'].isnull().sum()

np.int64(292364)

In [ ]:
df['anxiety_level'].value_counts()

Series([], Name: count, dtype: int64)

:

In [ ]:

import pandas as pd

df = pd.read_csv("../data/mental_health_dataset.csv")

print(df.head())

print(df['label'].value_counts())

In [ ]:
import pandas as pd

df = pd.read_csv("../data/mental_health_dataset.csv")

df.head()

In [ ]:
import pandas as pd

df = pd.read_csv("../data/mental_health_dataset.csv")

print(df.head())

print(df['label'].value_counts())

In [ ]:
import os

print(os.listdir("../data"))

In [1]:
import pandas as pd

df = pd.read_csv("../data/mental_health_dataset.csv")

print("First 5 rows:")
print(df.head())

print("\nLabel distribution:")
print(df['label'].value_counts())

First 5 rows:
         Timestamp  Gender        Country Occupation self_employed  \
0  8/27/2014 11:29  Female  United States  Corporate           NaN
1  8/27/2014 11:31  Female  United States  Corporate           NaN
2  8/27/2014 11:32  Female  United States  Corporate           NaN
3  8/27/2014 11:37  Female  United States  Corporate            No
4  8/27/2014 11:43  Female  United States  Corporate            No

  family_history treatment Days_Indoors Growing_Stress Changes_Habits  \
0             No       Yes    1-14 days            Yes             No
1            Yes       Yes    1-14 days            Yes             No
2            Yes       Yes    1-14 days            Yes             No
3            Yes       Yes    1-14 days            Yes             No
4            Yes       Yes    1-14 days            Yes             No

  Mental_Health_History Mood_Swings Coping_Struggles Work_Interest  \
0                   Yes      Medium               No            No
1                   Yes      Medium               No            No
2                   Yes      Medium               No            No
3                   Yes      Medium               No            No
4                   Yes      Medium               No            No

  Social_Weakness mental_health_interview care_options
0             Yes                      No     Not sure
1             Yes                      No           No
2             Yes                      No          Yes
3             Yes                   Maybe          Yes
4             Yes                      No          Yes

Label distribution:

KeyError: 'label'

In [5]:
import pandas as pd

df = pd.read_csv("../data/mental_health_dataset.csv")

df.head()
df['label'].value_counts()

KeyError: 'label'

In [6]:
import pandas as pd

df = pd.read_csv("../data/mental_health_dataset.csv")

print("Dataset Columns:")
print(df.columns)

print("\nFirst 5 rows:")
print(df.head())

Dataset Columns:
Index(['Timestamp', 'Gender', 'Country', 'Occupation', 'self_employed',
       'family_history', 'treatment', 'Days_Indoors', 'Growing_Stress',
       'Changes_Habits', 'Mental_Health_History', 'Mood_Swings',
       'Coping_Struggles', 'Work_Interest', 'Social_Weakness',
       'mental_health_interview', 'care_options'],
      dtype='object')

First 5 rows:
         Timestamp  Gender        Country Occupation self_employed  \
0  8/27/2014 11:29  Female  United States  Corporate           NaN
1  8/27/2014 11:31  Female  United States  Corporate           NaN
2  8/27/2014 11:32  Female  United States  Corporate           NaN
3  8/27/2014 11:37  Female  United States  Corporate            No
4  8/27/2014 11:43  Female  United States  Corporate            No

  family_history treatment Days_Indoors Growing_Stress Changes_Habits  \
0             No       Yes    1-14 days            Yes             No
1            Yes       Yes    1-14 days            Yes             No
2            Yes       Yes    1-14 days            Yes             No
3            Yes       Yes    1-14 days            Yes             No
4            Yes       Yes    1-14 days            Yes             No

  Mental_Health_History Mood_Swings Coping_Struggles Work_Interest  \
0                   Yes      Medium               No            No
1                   Yes      Medium               No            No
2                   Yes      Medium               No            No
3                   Yes      Medium               No            No
4                   Yes      Medium               No            No

  Social_Weakness mental_health_interview care_options
0             Yes                      No     Not sure
1             Yes                      No           No
2             Yes                      No          Yes
3             Yes                   Maybe          Yes
4             Yes                      No          Yes

In [7]:

import pandas as pd

df = pd.read_csv("../data/mental_health_dataset.csv")

# create label column
df['label'] = df['Growing_Stress']

print(df[['Growing_Stress','label']].head())

  Growing_Stress label
0            Yes   Yes
1            Yes   Yes
2            Yes   Yes
3            Yes   Yes
4            Yes   Yes

In [8]:
print(df['label'].value_counts())

label
Maybe    99985
Yes      99653
No       92726
Name: count, dtype: int64

In [9]:

df = df[['Gender','Occupation','family_history','Days_Indoors',
         'Mood_Swings','Coping_Struggles','Work_Interest',
         'Social_Weakness','label']]

print(df.head())

   Gender Occupation family_history Days_Indoors Mood_Swings Coping_Struggles  \
0  Female  Corporate             No    1-14 days      Medium               No
1  Female  Corporate            Yes    1-14 days      Medium               No
2  Female  Corporate            Yes    1-14 days      Medium               No
3  Female  Corporate            Yes    1-14 days      Medium               No
4  Female  Corporate            Yes    1-14 days      Medium               No

  Work_Interest Social_Weakness label
0            No             Yes   Yes
1            No             Yes   Yes
2            No             Yes   Yes
3            No             Yes   Yes
4            No             Yes   Yes

In [11]:
df = df.dropna()

In [12]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in df.columns:
    df[col] = encoder.fit_transform(df[col])

In [13]:
from sklearn.model_selection import train_test_split

X = df.drop("label", axis=1)
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:

from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

print("Model Accuracy:", accuracy_score(y_test, pred))

NameError: name 'model' is not defined

In [15]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\rajeev\desktop\exam anxiety detector\venv\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\rajeev\desktop\exam anxiety detector\venv\lib\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\rajeev\desktop\exam anxiety detector\venv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\rajeev\desktop\exam anxiety detector\venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\rajeev\desktop\exam anxiety detector\venv\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import pandas as pd

# Load dataset
df = pd.read_csv("../data/mental_health_dataset.csv")

# Create label column
df['label'] = df['Growing_Stress']

# Select useful columns
df = df[['Gender','Occupation','family_history','Days_Indoors',
         'Mood_Swings','Coping_Struggles','Work_Interest',
         'Social_Weakness','label']]

# Remove missing values
df = df.dropna()

# Encode categorical data
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in df.columns:
    df[col] = encoder.fit_transform(df[col])

# Split dataset
from sklearn.model_selection import train_test_split

X = df.drop("label", axis=1)
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

# Predict
from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

print("Model Accuracy:", accuracy_score(y_test, pred))

Model Accuracy: 0.927419492757341

In [17]:
df.head()

,Gender,Occupation,family_history,Days_Indoors,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,label
0,0,1,0,0,2,0,1,2,2
1,0,1,1,0,2,0,1,2,2
2,0,1,1,0,2,0,1,2,2
3,0,1,1,0,2,0,1,2,2
4,0,1,1,0,2,0,1,2,2

In [18]:
df.isnull().sum()

Gender              0
Occupation          0
family_history      0
Days_Indoors        0
Mood_Swings         0
Coping_Struggles    0
Work_Interest       0
Social_Weakness     0
label               0
dtype: int64

In [19]:
df['status'].value_counts()

KeyError: 'status'

In [1]:
import pandas as pd

df = pd.read_csv("../data/mental_health_dataset.csv")

print(df.columns)

print(df.head())

print(df['Growing_Stress'].value_counts())

Index(['Timestamp', 'Gender', 'Country', 'Occupation', 'self_employed',
       'family_history', 'treatment', 'Days_Indoors', 'Growing_Stress',
       'Changes_Habits', 'Mental_Health_History', 'Mood_Swings',
       'Coping_Struggles', 'Work_Interest', 'Social_Weakness',
       'mental_health_interview', 'care_options'],
      dtype='object')
         Timestamp  Gender        Country Occupation self_employed  \
0  8/27/2014 11:29  Female  United States  Corporate           NaN
1  8/27/2014 11:31  Female  United States  Corporate           NaN
2  8/27/2014 11:32  Female  United States  Corporate           NaN
3  8/27/2014 11:37  Female  United States  Corporate            No
4  8/27/2014 11:43  Female  United States  Corporate            No

  family_history treatment Days_Indoors Growing_Stress Changes_Habits  \
0             No       Yes    1-14 days            Yes             No
1            Yes       Yes    1-14 days            Yes             No
2            Yes       Yes    1-14 days            Yes             No
3            Yes       Yes    1-14 days            Yes             No
4            Yes       Yes    1-14 days            Yes             No

  Mental_Health_History Mood_Swings Coping_Struggles Work_Interest  \
0                   Yes      Medium               No            No
1                   Yes      Medium               No            No
2                   Yes      Medium               No            No
3                   Yes      Medium               No            No
4                   Yes      Medium               No            No

  Social_Weakness mental_health_interview care_options
0             Yes                      No     Not sure
1             Yes                      No           No
2             Yes                      No          Yes
3             Yes                   Maybe          Yes
4             Yes                      No          Yes
Growing_Stress
Maybe    99985
Yes      99653
No       92726
Name: count, dtype: int64

In [2]:
import pandas as pd

df = pd.read_csv("../data/mental_health_dataset.csv")

print("Columns in dataset:")
print(df.columns)

print("\nFirst 5 rows:")
print(df.head())

Columns in dataset:
Index(['Timestamp', 'Gender', 'Country', 'Occupation', 'self_employed',
       'family_history', 'treatment', 'Days_Indoors', 'Growing_Stress',
       'Changes_Habits', 'Mental_Health_History', 'Mood_Swings',
       'Coping_Struggles', 'Work_Interest', 'Social_Weakness',
       'mental_health_interview', 'care_options'],
      dtype='object')

First 5 rows:
         Timestamp  Gender        Country Occupation self_employed  \
0  8/27/2014 11:29  Female  United States  Corporate           NaN
1  8/27/2014 11:31  Female  United States  Corporate           NaN
2  8/27/2014 11:32  Female  United States  Corporate           NaN
3  8/27/2014 11:37  Female  United States  Corporate            No
4  8/27/2014 11:43  Female  United States  Corporate            No

  family_history treatment Days_Indoors Growing_Stress Changes_Habits  \
0             No       Yes    1-14 days            Yes             No
1            Yes       Yes    1-14 days            Yes             No
2            Yes       Yes    1-14 days            Yes             No
3            Yes       Yes    1-14 days            Yes             No
4            Yes       Yes    1-14 days            Yes             No

  Mental_Health_History Mood_Swings Coping_Struggles Work_Interest  \
0                   Yes      Medium               No            No
1                   Yes      Medium               No            No
2                   Yes      Medium               No            No
3                   Yes      Medium               No            No
4                   Yes      Medium               No            No

  Social_Weakness mental_health_interview care_options
0             Yes                      No     Not sure
1             Yes                      No           No
2             Yes                      No          Yes
3             Yes                   Maybe          Yes
4             Yes                      No          Yes

In [4]:
import pandas as pd

df = pd.read_csv("../data/mental_health_dataset.csv")

df.head()
df['label'].value_counts()

KeyError: 'label'

In [3]:
import pandas as pd

df = pd.read_csv("../data/mental_health_dataset.csv")

print("Columns:", df.columns)

print("\nFirst 5 rows:")
print(df.head())

print("\nLabel distribution:")
print(df['status'].value_counts())

Columns: Index(['Timestamp', 'Gender', 'Country', 'Occupation', 'self_employed',
       'family_history', 'treatment', 'Days_Indoors', 'Growing_Stress',
       'Changes_Habits', 'Mental_Health_History', 'Mood_Swings',
       'Coping_Struggles', 'Work_Interest', 'Social_Weakness',
       'mental_health_interview', 'care_options'],
      dtype='object')

First 5 rows:
         Timestamp  Gender        Country Occupation self_employed  \
0  8/27/2014 11:29  Female  United States  Corporate           NaN
1  8/27/2014 11:31  Female  United States  Corporate           NaN
2  8/27/2014 11:32  Female  United States  Corporate           NaN
3  8/27/2014 11:37  Female  United States  Corporate            No
4  8/27/2014 11:43  Female  United States  Corporate            No

  family_history treatment Days_Indoors Growing_Stress Changes_Habits  \
0             No       Yes    1-14 days            Yes             No
1            Yes       Yes    1-14 days            Yes             No
2            Yes       Yes    1-14 days            Yes             No
3            Yes       Yes    1-14 days            Yes             No
4            Yes       Yes    1-14 days            Yes             No

  Mental_Health_History Mood_Swings Coping_Struggles Work_Interest  \
0                   Yes      Medium               No            No
1                   Yes      Medium               No            No
2                   Yes      Medium               No            No
3                   Yes      Medium               No            No
4                   Yes      Medium               No            No

  Social_Weakness mental_health_interview care_options
0             Yes                      No     Not sure
1             Yes                      No           No
2             Yes                      No          Yes
3             Yes                   Maybe          Yes
4             Yes                      No          Yes

Label distribution:

KeyError: 'status'

In [1]:
model.save_pretrained("anxiety_model")
tokenizer.save_pretrained("anxiety_model")

NameError: name 'model' is not defined